language: python
python:
  - '3.6'
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql
env:
  global:
  - PGPORT=5433
  - DJANGO_SETTINGS_MODULE=consistently.settings
  - DATABASE_URL=postgresql://postgres@localhost/travis_ci_test
  - secure: TFNwsmXCi9jo8fDE0j7eeht+/yh1Ov96M5c+CqoQj9ILGqx48HSK7wQsvI7XXDikoSGjanBdv1SiC3FeuAzuOyIy4ExkQ5/bAn+aT2cHo/MzTMZxcOLWpS+/eqvXoTUfXi3PkvcGqAH7OLQb/Z5YCtsBQaZiC/UKfVRTXbtkFfIJa/CsVmoXBrhZq85ywYkiyK1QuJHB1v6BDTutW3u5ghI6ZUE4yiXsh6znC71VRDoyF8ZYJVVOMZ0JBkGD+tpAgycDbs37XaPcmLauDkaGLS6dbsLOGt4DJjwd+QpG3MyQTIsPAMyuAXva6sZjotjw+eJ6MgrhwDP19ogu9BXqTV/y/VbQfs5jTbUqKpZ3jhKvxFkIibtvTX/JtzyCWFYHrR0m+JmrtQoWiAIST2Wg2m8Uk2B1qEkzN+yk555AhVdXNg6sbQpx0c5nWOImw5+ldZP8jQbZ6T3rYxJyTkB/cYXsAogVTsDS3R1JWgUsUntwvVsgUzzBIqEED0QsvQWo9ZtTY0pV6cz3eagpS8qKoYoRZxfGUT7zAAcAOunO250Rpo8x7/CA6sKj1yh/sUZX8A8bNbM8tFo97r4n6caf/W3CJGGG/WE/uDxA4cbiFN04fDYHYDKh1PphAa2EKQdfoRJmrfDC3HtZ0A7iTgi3hajosA2xoDnt5WuzWnpoW3Y=
install:
  - npm install
  - pip install -U pip
  - pip install -r requirements.txt
  - python manage.py collectstatic
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py test -v3
notifications:
  email: false
