# Generated by Django 2.1.1 on 2018-10-06 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('integration_type', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting...'), ('passed', 'Passed'), ('failed', 'Failed')], default='waiting', max_length=20)),
                ('with_settings', models.TextField(blank=True, help_text='Archives the settings used to evaluate the integration', null=True)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Commit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HTMLValidation',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.Integration')),
                ('url_to_validate', models.URLField(blank=True, null=True)),
                ('deployment_delay', models.PositiveIntegerField(blank=True, help_text='How many seconds to wait after push before validation.', null=True)),
            ],
            options={
                'verbose_name': 'HTML Validation',
            },
            bases=('integrations.integration',),
        ),
        migrations.CreateModel(
            name='Travis',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.Integration')),
                ('build_time', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TravisCI',
            },
            bases=('integrations.integration',),
        ),
        migrations.AddField(
            model_name='integrationstatus',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.Integration'),
        ),
        migrations.AddField(
            model_name='integration',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Repository'),
        ),
    ]
