# Generated by Django 2.1.1 on 2018-09-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlvalidation',
            name='deployment_delay',
            field=models.PositiveIntegerField(blank=True, help_text='How many seconds to wait after push before validation.', null=True),
        ),
    ]
