# Generated by Django 2.1.1 on 2018-10-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coveralls',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.Integration')),
                ('build_time', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Coveralls',
            },
            bases=('integrations.integration',),
        ),
    ]
