# Generated by Django 2.1.1 on 2018-10-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_coveralls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSpeed',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.Integration')),
                ('url', models.URLField(blank=True, null=True)),
                ('deployment_delay', models.PositiveIntegerField(blank=True, help_text='How long before the app is live?', null=True)),
            ],
            options={
                'verbose_name': 'Google PageSpeed Insights',
            },
            bases=('integrations.integration',),
        ),
    ]
