# Generated by Django 2.1.1 on 2018-09-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20180921_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationstatus',
            name='with_settings',
            field=models.TextField(default='none', help_text='Archives the settings used to evaluate the integration'),
            preserve_default=False,
        ),
    ]
