# Generated by Django 2.1.1 on 2018-09-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationstatus_with_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationstatus',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationstatus',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='integrationstatus',
            name='with_settings',
            field=models.TextField(blank=True, help_text='Archives the settings used to evaluate the integration', null=True),
        ),
    ]
