# Generated by Django 2.1.1 on 2018-10-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_pagespeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagespeed',
            name='use_mobile_strategy',
            field=models.BooleanField(default=False),
        ),
    ]
