# Generated by Django 2.1.1 on 2018-09-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20180921_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationstatus',
            name='value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
