# Generated by Django 2.1.1 on 2018-10-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_auto_20180922_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travis',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.Integration')),
            ],
            options={
                'verbose_name': 'TravisCI',
            },
            bases=('integrations.integration',),
        ),
    ]
