# Generated by Django 2.1.1 on 2018-10-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_travis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Repository'),
        ),
    ]
