# Generated by Django 2.1.1 on 2018-10-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_auto_20181002_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrationstatus',
            old_name='celery_task_id',
            new_name='task_id',
        ),
    ]
