# Generated by Django 2.1.1 on 2018-10-06 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('fail_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_count', models.PositiveIntegerField(blank=True, null=True)),
                ('waiting_count', models.PositiveIntegerField(blank=True, null=True)),
                ('github_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('github_id', models.PositiveIntegerField(unique=True)),
                ('hook_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('prefix', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repos', to=settings.AUTH_USER_MODEL)),
                ('latest_commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repos.Commit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Repository'),
        ),
    ]
