# Generated by Django 2.0.2 on 2018-03-08 02:23

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('github_id', models.PositiveIntegerField(unique=True)),
                ('last_commit', models.DateTimeField(blank=True, null=True)),
                ('last_commit_name', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('name', 'username')},
        ),
        migrations.AlterIndexTogether(
            name='repository',
            index_together={('name', 'username')},
        ),
    ]
