# Generated by Django 2.1.1 on 2018-09-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_remove_repository_latest_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repos.Repository'),
            preserve_default=False,
        ),
    ]
