# Generated by Django 2.1.1 on 2018-09-23 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repos', '0003_commit_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='added_by',
        ),
        migrations.AddField(
            model_name='repository',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repos', to=settings.AUTH_USER_MODEL),
        ),
    ]
