# Generated by Django 2.1.1 on 2018-09-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_auto_20180923_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='latest_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repos.Commit'),
        ),
    ]
