# Generated by Django 2.1.1 on 2018-10-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0005_repository_latest_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='date',
            new_name='github_timestamp',
        ),
    ]
