# Generated by Django 2.1.1 on 2018-10-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0007_auto_20181002_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
