# Generated by Django 2.1.1 on 2018-10-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0008_commit_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='hook_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
