# Generated by Django 2.1.1 on 2018-10-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0009_repository_hook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='fail_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='pass_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='waiting_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
